### ISSUE TITLE
[Enhancement]: Refactor Code (styles) to use less "magic numbers"

### ISSUE THREAD

**Issue by moritzkirstein** [deltaDAO/mvg-portal#10]
thought(non-blocking): I prefer to work with multiple base values. When dealing with pixel-perfect positioning, we can add additional base values. But in my experience, it can be very difficult to maintain magic numbers across multiple projects. Using base values also gives non-designers a grid to follow when designing new elements. 

We need to discuss this in-depth after the hackathon @moritzkirstein Let's merge this PR.

_Originally posted by @oceanByte in https://github.com/deltaDAO/mvg-portal/pull/8#pullrequestreview-817784455_

**Comment by LucaMilanese90** [comment]
@moritzkirstein I think this issue can be closed as it was already addressed.
