### ISSUE TITLE
[BUG] Asset not consumable "insufficient tokens"

### ISSUE THREAD

**Issue by kaimeinke** [deltaDAO/mvg-portal#116]
## Summary
The free asset did:op:59205be7D61a5137685F9f15167DD8dEA65ff351 (data is free, algo is free) can not be consumed due to an error in the frontend. Error message states "insufficient tokens".

## Current Behavior
Can be reproduced on MVG and UDL portal
https://udl.portal.minimal-gaia-x.eu/asset/did:op:59205be7D61a5137685F9f15167DD8dEA65ff351
https://portal.minimal-gaia-x.eu/asset/did:op:59205be7D61a5137685F9f15167DD8dEA65ff351
  
## Expected Behavior
Consume button should not be greyed out and error message should not be presented.

Reported by Roberto Garcia, UDL.

**Comment by LucaMilanese90** [comment]
Should be fixed, waiting for the review to deploy. 
You can check the preview link here https://deploy-preview-117--mvg-portal-deltadao.netlify.app/asset/did:op:59205be7D61a5137685F9f15167DD8dEA65ff351

**Comment by oceanByte** [comment]
Updated code and function look fine to me. Can you verify this @kaimeinke?

**Comment by kaimeinke** [comment]
Doesn't work for me here. 
![image](https://user-images.githubusercontent.com/59994024/164178873-d6b3b99d-f84f-4e46-a0c1-845cb7a81096.png)
