### ISSUE TITLE
[Enhancement] Improve Header and Footer with Feature Links

### ISSUE THREAD

**Issue by kaimeinke** [deltaDAO/mvg-portal#118]
## Motivation / Problem
It is currently difficult for users to find all the resources of the Minimal Viable Gaia-X as the links are not being presented on the landing page. This should be as easy as possible for users and first-time visitors.

## Solution 
Include links to the following resources in the top and footer navigation:

- Catalogue https://catalogue.minimal-gaia-x.eu/
- Exchange Logging https://exchangelog.minimal-gaia-x.eu/
- Stats Page https://stats.minimal-gaia-x.eu/
- Onboarding https://onboarding-portal.lab.gaia-x.eu/
- Additonal on footer: Link to the Gaia-X Page https://gaia-x.eu/

Challenge: Link texts need to very brief, so i propose:

Catalogue, Logging, Stats, Identity for the top navigation. I am aware that this might create issues with the mobile navigation thus moving the links in the upper section of the page might be an alternative to the top navigation.

Top navigation
![image](https://user-images.githubusercontent.com/59994024/164784124-3bad8f1d-e355-48da-8237-096c6e9bc7af.png)

Alternative
![image](https://user-images.githubusercontent.com/59994024/164784305-2c79ad2b-7e79-4a63-a00a-b335e565d6bc.png)

Footer (does not replace the top nav, we need the links in the top nav)
<img width="898" alt="image" src="https://user-images.githubusercontent.com/59994024/164784374-5080d213-e761-4a10-aae0-360c425523d2.png">

## Alternatives
Create a section like the features assets section that leads to the additional pages and teasers them briefly and describes their functionality.

## Additional context
User centricity needs to be in focus. As we lack a structured user testing panel we need to change the perspective to the one of a newcomer frequently.

**Comment by LucaMilanese90** [comment]
@moritzkirstein I just realized we are not using the "new" footer design on the current main branch of the MVG portal, I know it was in the `feat/mvp` branch, should I bring that back or is there another reason why we are not using it? It would definitely be easier to place all these new links in there. 
As for the navbar, I would keep the 3 current routes (Publish, Verify and Profile) on a first access level and add a 4th menu item with a dropdown for all the remaining links listed by Kai (similar to what we have in the Academy)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/20192135/175962063-6d5ade5c-413d-4570-913d-a700c2f8edfd.gif)

This would preserve the mobile view while giving us the ability to add virtually as many links as we want.
Should I move forward or do you have different ideas?
