### ISSUE TITLE
[Enhancement] Compute-to-Data Image

### ISSUE THREAD

**Issue by moritzkirstein** [deltaDAO/mvg-portal#15]
## Motivation / Problem
![grafik](https://user-images.githubusercontent.com/28757404/144138388-bb0a90af-a56b-4779-b17c-6bfe4ae09614.png)

- From an UX perspective it is not fully clear, that the image is extendable / resizeable
- The resized picture (bigger) needs better resolution

## Solution 
- add the `zoom-in` cursor on hover
- Use bigger resolution for CtD graphic

## Additional context
Please add the graphic below in a comment @MeikeMolitor

**Comment by MeikeMolitor** [comment]
![CtD](https://user-images.githubusercontent.com/88214332/144143902-5c2dd7ea-3928-48ee-bd21-59fddc37a9c8.png)
