### ISSUE TITLE
[BUG] Privacy Policy Table of contents links don't work

### ISSUE THREAD

**Issue by ThomasKomenda** [deltaDAO/mvg-portal#158]
## Summary
When you click our privacy policy in one of our portals, the table of content links don't lead to the corresponding location, but nothing happens
## Current Behavior
nothing happens
  
## Expected Behavior
links lead to the corresponding location

## Steps to Reproduce

1. open one of our portals (MVG, EuProGigant)
2. scroll down to privacy policy
3. click privacy policy
4. click on one of the table of content links
5. fail :(

![image](https://user-images.githubusercontent.com/99354530/178613447-fd2b05f7-dee0-4aaf-8285-7e8dfa5d3b41.png)

**Comment by moritzkirstein** [comment]
Fix is implemented in https://github.com/deltaDAO/portal-euprogigant/pull/32 - please refer to the [preview](https://development--portal-euprogigant-deltadao.netlify.app/) @ThomasKomenda to confirm this is working as expected.
Fix can then be implemented here @LucaMilanese90

**Comment by ThomasKomenda** [comment]
Preview version works as intended @LucaMilanese90 @moritzkirstein
