### ISSUE TITLE
[BUG] Asset details page broken

### ISSUE THREAD

**Issue by moritzkirstein** [deltaDAO/mvg-portal#183]
## Summary

Our asset details page crashes for certain assets: We introduced a new asset type that can currently not be handled by our portal. For now we want to simply remove these assets from the portal.
(Example: https://deploy-preview-173--mvg-portal-deltadao.netlify.app/asset/did:op:94E413D68c2f0c2DB39370C012521CC10a335eca)

## Solution
Adjust aquarius baseQuery to exclude assets of type 'thing' by default
```metadata.attributes.main.type = 'thing' ```

**Comment by LucaMilanese90** [comment]
Are you sure the query is for `metadata.attributes.main.type` and not `service.attributes.main.type`?
