### ISSUE TITLE
[Feature] Subpage: Edge Computing

### ISSUE THREAD

**Issue by moritzkirstein** [deltaDAO/mvg-portal#185]
## Motivation / Problem

We need to communicate the Compute-to-Edge paradigm on the MVG and make it visible.

## Solution

We should introduce a new subpage **Edge Computing**, which
- explains the CtE concept in a brief section (content will be added to the issue)
- lists relevant things as new `edge` asset teaser type

## Additional Information:
- Query aquarius for assets with `metadata.attributes.main.type = thing` and display with AssetTeaser:
  - display new type ‘Edge Device’ (instead of 'dataset' | ' algorithm'), icon see below
  - title as currently
  - network as currently
  - no price
  - no description, instead:
    - show device model `findServiceByType('edge').provider.device.model`
    - show number of available assets `findServiceByType('edge').attributes.main.availableServices.length`

In the first iteration we do not need asset details page for edge devices → disable teasers to be not clickable

--- 
Icon for the new type 
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path fill="currentColor" d="M30 19h-4v-4h-2v9H8V8h9V6h-4V2h-2v4H8a2.002 2.002 0 0 0-2 2v3H2v2h4v6H2v2h4v3a2.002 2.002 0 0 0 2 2h3v4h2v-4h6v4h2v-4h3a2.003 2.003 0 0 0 2-2v-3h4Z"/><path fill="currentColor" d="M21 21H11V11h10zm-8-2h6v-6h-6zm18-6h-2A10.012 10.012 0 0 0 19 3V1a12.013 12.013 0 0 1 12 12z"/><path fill="currentColor" d="M26 13h-2a5.006 5.006 0 0 0-5-5V6a7.008 7.008 0 0 1 7 7Z"/></svg>
```

**Comment by moritzkirstein** [comment]
**Edit:** changed `infrasctructure` to `edge device`

**Comment by LucaMilanese90** [comment]
>     * show number of available assets `findServiceByType('edge').attributes.main.availableServices.length`

Currently I don't see `availableServices` between the asset keys in the ddo `edge` service, is it because the published assets are incomplete or is there a different field I should be looking for?

**Comment by moritzkirstein** [comment]
Yes currently no device has any assets linked to it. This is expected behaviour 👍
