### ISSUE TITLE
[Enhancement] checkbox titles and disclaimer

### ISSUE THREAD

**Issue by MeikeMolitor** [deltaDAO/mvg-portal#188]
I think it makes more sense to transform the first checkbox in a disclaimer below the submit button which states: "When you click submit, your wallet address and public key will be transmitted to a smart contract stored permanently on the Gaia-X testnet."
Regarding the second check-box, could we please change the heading to "Metadata confirmation"?

![](https://user-images.githubusercontent.com/28757404/184613200-eabcc0af-8ddb-4a6e-8060-7fdd4cca357c.png)

**Comment by LucaMilanese90** [comment]
In this case the disclaimer would just be a simple message, right? Nothing to confirm for the user or to register in the DDO

**Comment by MeikeMolitor** [comment]
> In this case the disclaimer would just be a simple message, right? Nothing to confirm for the user or to register in the DDO

Correct.
