### ISSUE TITLE
[Enhancement] Menu & UX Update (WIP)

### ISSUE THREAD

**Issue by moritzkirstein** [deltaDAO/mvg-portal#201]
## Motivation / Problem

We want to enhance usability and the MVG menu / navigation.

## Solution 

Mock: https://www.figma.com/file/mgBcp6CwzOl1e4hNIfaBKV/MVG-Nav?node-id=1%3A2

- [x] Move statistics to footer
- [x] Add `Catalogue` to navigation -> links to searchpage
- [x] Update ecosystems dropdown to display relevant projects
- [x] Move Profile to wallet dropdown (account dropdown)
- [x] Include Debug Mode (settings) in account dropdown
- [x] Include link to or setting to turn on Onboarding in account dropdown
- [x] Remove settings button

**Comment by LucaMilanese90** [comment]
- From the design in Figma I don't see the "edge computing" menu link, which is the largest string we have and would force the navigation links to basically be on a separate row on pretty much all display sizes, is this ok? 
- What about the `currency` selector in settings? Are we removing it?
- Both the moveID and FMDM portals are not currently public (password protected), should we already include them in the ecosystem list or is it something for later?

**Comment by moritzkirstein** [comment]
Sorry forgot about edge computing:
- [ ] add "Edge Devices" as a "filter" on search page (catalogue) and use this to display edge computing
- We will remove currency for now and use EUR as default value
- FMDM should be publicly available after this sprint and therefore can be included. moveID can be included at a later point (maybe next sprint), once content is provided
