### ISSUE TITLE
[BUG] Not displaying algorithms from trusted publishers for dataset using publisherTrustedAlgorithmPublishers

### ISSUE THREAD

**Issue by rogargon** [deltaDAO/mvg-portal#388]
## Summary
Trying to make that datasets can be computed by any algorithm from trusted publishers. Using Nautilus, I published a new dataset that can be accessed just through compute and configured it to trust any algorithm from a trusted publisher following what is described in https://docs.oceanprotocol.com/core-concepts/did-ddo#compute-options

The code is:
```
asset.services[0].compute = {
        allowNetworkAccess: false,
        allowRawAlgorithm: false,
        publisherTrustedAlgorithmPublishers: ['0x...'],
        publisherTrustedAlgorithms: []
    };
```

The dataset is published with the expected metadata, for instance: https://mvg.angliru.udl.cat/asset/did:op:87d5d3e9b3b34a9058b3013369c8f61dfbbe873657a30779adbee22688042f00

## Current Behavior

Though there are algorithms published by the trusted addresses, they are not listed as options to run a compute job on the dataset.
  
## Expected Behavior

The algorithms published by any of the trusted publishers should appear. Thus, not requiring to add them manually.

**Comment by LucaMilanese90** [comment]
@rogargon thanks for letting us know, I drafted a little fix for this issue, could you please verify at this preview link if the algorithms show up as expected? https://mvg-portal-git-fix-publisher-trusted-algo-publishers-deltadao.vercel.app/asset/did:op:87d5d3e9b3b34a9058b3013369c8f61dfbbe873657a30779adbee22688042f00

**Comment by moritzkirstein** [comment]
@rogargon I merged the fix. Feel free to re-open if you still see issues with the behaviour on your end.

**Comment by rogargon** [comment]
Thanks for solving the issue so quickly and efficiently. Our MVG is now rebased and redeployed, and works perfectly. This feature streamlines a lot publishing new datasets using Nautilus.
