### ISSUE TITLE
[BUG] Credetials is not enforced, at least in the case of an algorithm

### ISSUE THREAD

**Issue by rogargon** [deltaDAO/mvg-portal#395]
## Summary

After publishing an algorithm and restricting its use using the credentials feature:

```json
{
  "allow": [
      {
          "type": "address",
          "values": ["0x620...6822"]
      }
  ],
  "deny": []
}
```

The credentials are not enforced and the algorithm can be run by other users different from the allowed one.

Full details about the algorithm metadata:
https://aquarius510.v4.delta-dao.com/api/aquarius/assets/ddo/did:op:bb614aa49bb6b61c35ca47c587b0034ed55dcdc9b4c002b79e5c93045f989a86

And the executions by different users (one authorized and the other not) have been done on dataset `did:op:10724ed83260936b6162122b6653d37e7ce8d9656355573a6def945aebcc6dda`

## Current Behavior

Users that are not among the ones allowed through the credentials mechanism can execute the algorithm.
  
## Expected Behavior

Just the users explicitly granted access through credentials can execute the algorithm.

**Comment by moritzkirstein** [comment]
Hi @rogargon,
sorry for the delay. We just merged a PR that aims to fix this in our portal UX. Feel free to have a look at #403 which is currently being deployed to our live portal.
However, the enforcement of this rule needs to be handled on [provider](https://github.com/oceanprotocol/provider/issues) side. If execution of a restricted algorithm was still possible this should be raised as an issue in that repository.
