### ISSUE TITLE
[Enhancement] Improve Error Handling Dialogue on Service Consumption

### ISSUE THREAD

**Issue by kaimeinke** [deltaDAO/mvg-portal#40]
## Motivation / Problem
As a Gaia-X Consumer I want to consume a given data service offering the very first time. Often, in most cases actually, the initial transaction fails in the frontend and I am presented a "red" error without further explanation.

![image](https://user-images.githubusercontent.com/59994024/150992038-4d162c36-a7a5-4e10-9488-905e2d666d98.png)

## Solution 
Try again until it works.

## Reproduction
Apple, Brave, MetaMask, Resource: https://forever.portal.minimal-gaia-x.eu/asset/did:op:17fB3b4B571351bf8368c6c7Bfe9766F548C7201

Note: It does not happen every time and on every service, but overall this is not working properly and affects user experience.

## Alternatives
Improvement Proposal: Change the error message to "Transaction error. Please try again."

## Alternative 2
Fix the underlying issue.

**Comment by moritzkirstein** [comment]
@LucaMilanese90 please have a closer look at why the error is getting displayed on the first compute/consumption request (about 90% of the time). We can decide on the solution when we know more about the error -> Maybe its a simple frontend error like not setting some variable correctly

While on that we can already adjust the displayed error message: `"Error buying datatoken. Please try again."`
