### ISSUE TITLE
[Enhancement] Adjust CtD content

### ISSUE THREAD

**Issue by moritzkirstein** [deltaDAO/mvg-portal#48]
## Motivation / Problem
![grafik](https://user-images.githubusercontent.com/28757404/154141905-d35ed8cd-5811-47de-b40f-abf75d87c4e7.png)

We currently have a section outlining CtD benefits with a link to the academy.
This should be adjusted to be more "introductory", something along the lines of "The CtD paradigm", or "This demonstrator utilizes CtD" -> see #74 for final wording decisions.

The graphic(s) - for both paragraphs - needs to be (re)designed according to GX media guidelines.

## Solution 
- [x] discuss and decide on final content
- [x] change content
- [x] adjust graphic design
- [x] change graphics
- [x] remove the cta

**Comment by MeikeMolitor** [comment]
Adjusted graphic
![ctd_gx](https://user-images.githubusercontent.com/88214332/156184265-676a4bcf-ca20-4206-b058-9b0ce85c406d.svg)

**Comment by kaimeinke** [comment]
I would suggest to include "technical data sovereignty" as it is a more specific and stronger claim.
