### ISSUE TITLE
Linking a dataset to an algorithm

### ISSUE THREAD

**Issue by michaelvff** [deltaDAO/mvg-portal#517]
Hi
We need some guidance regarding how we can link a dataset to an algorithm. We have created and published a simple algorithm that should take another dataset that we have published as its input, but we've not been able to link the two together. 

Dataset
https://portal.pontus-x.eu/asset/did:op:6acda2af7be82f857053f449bb9186aa19536268abc1b0233c340a2042633dec

Compute algorithm
https://portal.pontus-x.eu/asset/did:op:8a691006d5539eac65e0a105e15479ff02648269a58d85b1801709cf984b1783

Do you have any guidance for how we can complete this step?
Thanks

**Comment by michaelvff** [comment]
When we have tried to edit compute settings, to link a dataset and an algorithm together, but we do not get the option to edit compute settings. We only get the edit metadata option.  Please see attached screenshots

<img width="532" alt="with Button" src="https://github.com/deltaDAO/mvg-portal/assets/161824276/b4962314-0ec2-4453-b28f-bfcc234ce26a">
<img width="746" alt="without button" src="https://github.com/deltaDAO/mvg-portal/assets/161824276/e67ef2ba-aaee-4f5f-80ce-9184d3b3a044">

**Comment by Abrom8** [comment]
Try to republish the dataset as `compute` type and the option should appear in the frontend.
