### ISSUE TITLE
[Feature] Quote Section

### ISSUE THREAD

**Issue by moritzkirstein** [deltaDAO/mvg-portal#53]
## Motivation / Problem
We want to display some quotes regarding the MVG on the portal landing page.

## Solution
- [x] prepare design on figma
- [x] implement design

**Comment by moritzkirstein** [comment]
Initial idea is to have a component similar to:
![grafik](https://user-images.githubusercontent.com/28757404/155213682-b7dba60a-4f0c-466d-8081-f4a4ab3d52dc.png)

Took this example from https://tailwindcss.com

Maybe you can research some alternatives or start with the above example and we go from there @LucaMilanese90 ?

**Comment by LucaMilanese90** [comment]
How many quotes do we plan to use? Are they going to be more personal opinions or companies statements?
We already have a section on the homepage that uses the design of picture/text and then mirrors it on the next section, and we are already using a lot of cards between 3rd party portals and featured use cases. To not repeat it I would suggest to use a timed scrolled carousel with a more open structure like in this example:

![Screenshot 2022-02-23 at 11 23 12](https://user-images.githubusercontent.com/20192135/155300866-3d426f4a-b35f-42b6-a1fa-61f7759deea1.png)

We can also integrate a picture somewhere in it if we know we are going to have one for each quote

**Comment by LucaMilanese90** [comment]
Since we are not speaking about companies the pictures could replace the logos on top, keeping the effect of having them B/W and switching to color (and maybe increasing the dimension) when they are displayed
