### ISSUE TITLE
[Enhancement] Remove Video Section

### ISSUE THREAD

**Issue by moritzkirstein** [deltaDAO/mvg-portal#63]
## Motivation / Problem
We need to remove the YT video from the landing page due to privacy implications.

## Solution 
For now, we should simply remove the video player and use a placeholder image. We can use the CtD section image.

## Notes
Since this is the only place where we actually displayed any video, we should also remove all related dependencies.

**Comment by LucaMilanese90** [comment]
Do we leave the link to the youtube video on the "Learn More" button or do we remove that as well?
