### ISSUE TITLE
[BUG] Profile: Published View does not show SAAS if no filter was selected

### ISSUE THREAD

**Issue by contact-yme** [deltaDAO/mvg-portal#637]
## Summary
In the Profile of a participant, there is a view for all published offerings of this participant. When no filter is selected, datasets AND algorithms are displayed. SaaS-type offerings are only displayed if the saas-checkbox is checked. 

## Current Behavior
 SaaS-type offerings are only displayed if the saas-checkbox is checked. If no filter is applied, only datasets and algorithms are displayed. 
  
## Expected Behavior
If no filter is applied, display all offerings. Datasets, Algorithms and SaaS.

## Steps to Reproduce
I found it at this profile: https://portal.pontus-x.eu/profile/0xD9BAB8E6279CE41C2bC3f1D44ceF855235e0CdB7
This profile only has 3 offerings which are all saas-offerings. They only show if saas is selected.

In comparison, take a look at https://portal.pontus-x.eu/profile/0x3560626F234eD181E807E4e31ded56D9aca1ac58
We do offer datasets and algorithms. Without selection, both types are displayed.

**Comment by moritzkirstein** [comment]
Thanks for the bug report @contact-yme 
The issue has been fixed and should be available on the live portal in just a bit.
