### ISSUE TITLE
[Enhancement] Improve MVG Wording

### ISSUE THREAD

**Issue by kaimeinke** [deltaDAO/mvg-portal#74]
## Motivation / Problem
The MVG Portal needs to be adjusted for the Handover to Gaia-X. 

## Heading

- [x] Change "MVG Portal Demonstrator" to "Minimal Viable Gaia-X"
- [x] Change "A platform to find, publish and consume Data Services in the Gaia-X Test Network." to "A portal to publish, find and consume service offerings in a Gaia-X test network".
- [x] Remove Headline "This MVG portal demonstrator was built for the 2nd Gaia-X hackathon."
- [x] Change DLT paragraph to "The principle of a federated data infrastructure is a perfect fit for Distributed Ledger Technology. [Ocean Protocol](https://oceanprotocol.com/) offers a free open-source technology stack, leveraging DLT and open-source components like Kubernetes, Docker, React, etc. to give control to the consumers, service providers and federators of an ecosystem. This Minimal Viable Gaia-X demonstrator is built using Ocean Protocol components to showcase how a Minimal Viable Gaia-X and Federation Services on DLT can work, today."
- [x] Change Video to architecture graphic -> https://github.com/deltaDAO/mvg-portal/issues/48#issuecomment-1057157396
- [x] Change "Compute-to-Data and its benefits" to "The Compute-to-Data paradigm"
- [x] Change "All data services" to "All service offerings"

## Profile Page

- [x] Remove "Liquidity in Own Assets"
- [x] Remove "Total Liquidity"
- [ ] Optional Remove 3Box Profile Overall, it does not work and just include Sales and Published

## Misc

- [ ] Optional Remove Currency Conversion

**Comment by moritzkirstein** [comment]
Skipping optional requirements for now. We can keep 3box links to avoid overhead for now.
