### ISSUE TITLE
[Enhancement] Switch to correct network button should have disabled style 

### ISSUE THREAD

**Issue by LucaMilanese90** [deltaDAO/mvg-portal#81]
## Motivation / Problem
When the user is connected through a different network compared to the asset displayed, the button to automatically switch to the correct network looks like it can't be clicked.
<img width="552" alt="Screenshot 2022-03-04 at 11 34 56" src="https://user-images.githubusercontent.com/20192135/156781424-f5628098-7a60-4de6-893e-1f6bc8fb36f1.png">

**Comment by moritzkirstein** [comment]
Agreed. Button should be displayed as "enabled"
