### ISSUE TITLE
Problem when trying do edit metadata

### ISSUE THREAD

**Issue by ThomasKomenda** [deltaDAO/mvg-portal#89]
## Summary
white screen when clicking edit metadata: https://portal.minimal-gaia-x.eu/asset/did:op:De7A1AB5db11de81513B837f69dEC8581DDB1035

## Current Behavior
white screen, nothing to see
  
## Expected Behavior
metadata edit mask appears and metadata can be edited

## Steps to Reproduce
1. go to data set: https://portal.minimal-gaia-x.eu/asset/did:op:De7A1AB5db11de81513B837f69dEC8581DDB1035
2. login metamask account: 0xa76Fa6837A6ffc9F123F2193717A5965c68B0cbA
3. click edit metadata
![image](https://user-images.githubusercontent.com/99354530/157498758-9d1e007d-27c9-4665-ab24-d52ef143e435.png)

**Comment by kaimeinke** [comment]
I am able to reproduce this behaviour.

**Comment by LucaMilanese90** [comment]
I don't have the credentials to log in with that wallet so I can't test why it's not working
